### PR TITLE
updated comments

### PR DESCRIPTION
**Pull request by CGMcAllansmith**
@Vogog or @hanjane can you please review my comments and confirm merge to master.

### CODE REVIEW

**Comment by Vogog** [comment]
Looks good, am I correct in saying this is straight line code that uses the camera to check pixels? Because the code doesn't seem to do anything with this data, such as adjusting the avc's path.
I can look at it tomorrow too I suppose.

**Comment by CGMcAllansmith** [comment]
The setmotor commands should run after the for loops because they're all within the while loop. When I did the table top test they would slow down and speed up depending on where the line was. But when I tested it on the course the right wheel wasn't efficient and I don't know if it was hardware or code related. (I replaced and tested the motors)

**Comment by Vogog** [comment]
As long as your code for the right wheel mirrors the code for the left wheel, it should work the same, so it's probably a hardware issue
Also, my mistake, I didn't see the rest of the code which was not changed.
From what I can tell, it should work, I'll see for myself tomorrow.
This should actually allow the AVC to move up until the intersections section of the maze correctly.

**Comment by Vogog** [comment]
We can merge it tomorrow when we've confirmed it hasn't broken overnight.

**Comment by CGMcAllansmith** [comment]
Haha let's hope. I haven't wired up the new motors but I tested them on the same voltage and they rotated at the same speed.

**Pull request merged**
